### ISSUE TITLE
[FEATURE] MLCommons Integration

### ISSUE THREAD

**Issue by dhrubo-os** [opensearch-project/opensearch-py-ml#104]
**Is your feature request related to a problem?**

We want to integrate all the ML-Commons api to opensearch-py-ml.

Right now following apis are supported:

1. Upload Model
2. Load model
3. Get task information
4. Get model information
5. Unload model
6. Delete model

We want to have support for following apis:

1. Train --> https://opensearch.org/docs/latest/ml-commons-plugin/api/#train-model
2. Predict --> https://opensearch.org/docs/latest/ml-commons-plugin/api/#predict
3. Train and Predict  --> https://opensearch.org/docs/latest/ml-commons-plugin/api/#train-and-predict
4. Search Task --> https://opensearch.org/docs/latest/ml-commons-plugin/api/#search-task
5. Delete Task --> https://opensearch.org/docs/latest/ml-commons-plugin/api/#delete-task                   ---------> This is done.
6. Profile api --> https://opensearch.org/docs/latest/ml-commons-plugin/api/#profile
7. Search model --> https://opensearch.org/docs/latest/ml-commons-plugin/api/#search-model
8. Execute api --> https://opensearch.org/docs/latest/ml-commons-plugin/api/#execute : For testing after development, we can use this request:

```
POST _plugins/_ml/_execute/local_sample_calculator
{
    "operation": "max",
    "input_data": [1.0, 2.0, 3.0]
}
```
So, to implement this request python function can expect two variables:
1. algorithm name
2. input request --> here we need to check the input validation like if the input string is a valid json object or not.

**Comment by Merey1508** [comment]
Hi, everyone! I wanted to let you know that I am currently focusing my efforts on the Profile API (№6). 

@dhrubo-os, I've noticed that we have two identical tasks (№4 and №7) in our API support list. Perhaps we can review and clarify if there are any differences between the two, or if one of them can be removed to avoid confusion?

**Comment by dhrubo-os** [comment]
> 

Thanks.

**Comment by dhrubo-os** [comment]
> Hi, everyone! I wanted to let you know that I am currently focusing my efforts on the Profile API (№6).
> 
> @dhrubo-os, I've noticed that we have two identical tasks (№4 and №7) in our API support list. Perhaps we can review and clarify if there are any differences between the two, or if one of them can be removed to avoid confusion?

@Merey1508 Yes, you are right. Removed the duplicate task. Thanks

**Comment by dhrubo-os** [comment]
Few of the tasks are completed and new issues are created for for the remaining tasks. We can close this issue.

**Comment by dhrubo-os** [comment]
Few of the tasks are completed and new issues are created for for the remaining tasks. We can close this issue.
