### ISSUE TITLE
[FEATURE] add support for MLCommons Pre-trained models support

### ISSUE THREAD

**Issue by dhrubo-os** [opensearch-project/opensearch-py-ml#106]
**Is your feature request related to a problem?**

No.

From Opensearch 2.6 version, MLCommons support [Pre-trained models](https://opensearch.org/docs/latest/ml-commons-plugin/pretrained-models/).

But from opensearch-py-ml's [upload_model](https://github.com/opensearch-project/opensearch-py-ml/blob/main/opensearch_py_ml/ml_commons/ml_commons_client.py#L28-L33) doesn't support that yet. 

Either we need to add another function `upload_pretrained_model` or include uploading pre-trained model feature in `upload_model` method

**Comment by AlibiZhenis** [comment]
May I work on this as part of CCI?

**Comment by dhrubo-os** [comment]
Yes, definitely.

**Comment by AlibiZhenis** [comment]
I created a PR, but I'm having trouble connecting it to this issue.

**Comment by dhrubo-os** [comment]
> I created a PR, but I'm having trouble connecting it to this issue.

I guess you can mention this issue number in your repo.
