### ISSUE TITLE
[FEATURE] Need to add backward compatibility test.

### ISSUE THREAD

**Issue by dhrubo-os** [opensearch-project/opensearch-py-ml#117]
Currently `opensearch-py-ml` has integration test for only [opensearch version 2.5.0](https://github.com/opensearch-project/opensearch-py-ml/blob/main/.github/workflows/integration.yml#L15)

We also need to add integration for previous version (`2.7.0`) and the most updated version (`2.9.0`).

That will complete this backward compatibility test.

Then we can close [this issue](https://github.com/opensearch-project/opensearch-py-ml/issues/88)

**Comment by zhonniks** [comment]
Good day ,@dhrubo-os , can i work on this issue?

**Comment by dhrubo-os** [comment]
Sure. Please go ahead.

**Comment by Yerzhaisang** [comment]
I see the commit by @zhonniks , but no run workflow. Can we test the fix?

**Comment by dhrubo-os** [comment]
@Yerzhaisang This issue is not completed yet. IF you want you can pick this issue.

**Comment by rawwar** [comment]
@dhrubo-os , does #332  complete this feature as well?

**Comment by dhrubo-os** [comment]
Yeah, I believe it does. Please mention this issue also in your PR as well.
