### ISSUE TITLE
[CCI][FEATURE] Add test coverage statistics to Codecov

### ISSUE THREAD

**Issue by bl1nkker** [opensearch-project/opensearch-py-ml#118]
**Is your feature request related to a problem?**
The project currently is not integrated with codecov.io, while [many other repositories](https://app.codecov.io/gh/opensearch-project/opensearch-js) already display test coverage on the web interface.

**What solution would you like?**
Add codecov integration

**Comment by bl1nkker** [comment]
yes, I'm already working on it

**Comment by bl1nkker** [comment]
as it turned out there are some problems associated with the tests. I will wait for the response from the mentors on [this issue](https://github.com/opensearch-project/opensearch-py-ml/issues/124)

**Comment by dhrubo-os** [comment]
Closing the issue on favor of [this PR](https://github.com/opensearch-project/opensearch-py-ml/pull/138)
