### ISSUE TITLE
[FEATURE] Rename APIs for model serving framework 

### ISSUE THREAD

**Issue by dhrubo-os** [opensearch-project/opensearch-py-ml#122]
According to [this issue](https://github.com/opensearch-project/ml-commons/issues/823), api endpoints are going to be changes in Model Serving framework in MLCommons.

As `opensearch-py-ml` works as a client for MLCommons, we also need to reflect that changes in our repo to support the new updates APIs. 

1. upload_model --> register_model
2. load_model --> deploy_model
3. unload_model --> undeploy_model

P.S --> This changes needs to be done after OS 2.7 release.

Issue in MLCommons: https://github.com/opensearch-project/ml-commons/issues/823

**Comment by AlibiZhenis** [comment]
2.7 should be out around today. I can pick this up.

**Comment by dhrubo-os** [comment]
> 2.7 should be out around today. I can pick this up.

Yes, please go ahead.
