### ISSUE TITLE
[CCI][FEATURE] Should tests be run during ci/cd?

### ISSUE THREAD

**Issue by bl1nkker** [opensearch-project/opensearch-py-ml#124]
**Is your feature request related to a problem?**
At the moment I'm working on [codecov integration issue](https://github.com/opensearch-project/opensearch-py-ml/issues/118). Having looked into the [ci.yml](https://github.com/opensearch-project/opensearch-py-ml/blob/main/.github/workflows/ci.yml), I saw that tests are not being carried out on Linux. In my opinion, this is a big problem, given that in [opensearch-py repository](https://github.com/opensearch-project/opensearch-py/blob/51eb6e5cca0a0970334ac228e93a4bd025b73373/.github/workflows/ci.yml#L38), tests are run during ci / cd

**What solution would you like?**
Running tests during CI/CD

**Do you have any additional context?**
Additionally, I want to clarify something. In opensearch-py, [Jenkins/Github actions only run server tests](https://github.com/opensearch-project/opensearch-py/blob/51eb6e5cca0a0970334ac228e93a4bd025b73373/test_opensearchpy/run_tests.py#L123). And there is no clear separation of tests in **this** repository. Should tests be run at all?

**Comment by dhrubo-os** [comment]
Most of our tests are mostly integration test as we need to pull data from opensearch or upload model to opensearch. So writing only unit test doesn't make enough sense for most of the cases.

Why do you think tests are not carried out on linux is a problem? 

Tests are being run in Docker. One thing we can do is after running the tests in docker and generating the xml file of the code coverage in docker we can copy that file to the linux like [this](https://github.com/opensearch-project/opensearch-py-ml/blob/main/.ci/run-repository.sh#L61) 

Please let me know what do you think?

**Comment by bl1nkker** [comment]
Yeah, got it!
