### ISSUE TITLE
[BUG] Step from guide says model deployed but failed

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/opensearch-py-ml#207]
**What is the bug?**
In the sphinx docs it says the model deployed successfully but the output says it failed. 
https://github.com/opensearch-project/opensearch-py-ml/blob/1237aa61bb40cf6cef06002cffa02093ef4b2023/docs/source/examples/demo_ml_commons_integration.ipynb#L318C1-L318C414)

**How can one reproduce the bug?**
1. Go to 'https://opensearch-project.github.io/opensearch-py-ml/examples/demo_ml_commons_integration.html#Step-2:-Load-Model
2. View the result. It says it deployed but the output says it failed.

**Comment by dhrubo-os** [comment]
Thanks for the catch. Fixed in [this PR](https://github.com/opensearch-project/opensearch-py-ml/pull/208). 

Updated doc: https://opensearch-project.github.io/opensearch-py-ml/examples/demo_ml_commons_integration.html
