### ISSUE TITLE
[FEATURE] Add missing files and workflows

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/opensearch-py-ml#24]
**Is your feature request related to a problem?**
The following files are missing:
- [ADMINS.md](https://github.com/opensearch-project/opensearch-py/blob/main/ADMINS.md)
- [COMPATIBILITY.md](https://github.com/opensearch-project/opensearch-py/blob/main/COMPATIBILITY.md)
- [Whitesource configuration](https://github.com/opensearch-project/opensearch-py/blob/main/.whitesource)
- [RELEASING.md](https://github.com/opensearch-project/opensearch-py/blob/main/RELEASING.md)
- [SECURITY.md](https://github.com/opensearch-project/opensearch-py/blob/main/SECURITY.md)
- Mend for Github (CVEs)
- CODEOWNERS
- [CHANGELOG](https://github.com/opensearch-project/opensearch-py/blob/main/CHANGELOG.md) and [changelog verifier](https://github.com/opensearch-project/opensearch-py/blob/main/.github/workflows/changelog_verifier.yml)
- Other necessary client workflows listed [here](https://github.com/opensearch-project/opensearch-clients/blob/main/WORKFLOWS.md)

**Comment by dhrubo-os** [comment]
Sure, please go ahead. I'm assigning this issue to you then. Thanks.

**Comment by dhrubo-os** [comment]
Closing this issue as all the tasks mentioned here are done.
