### ISSUE TITLE
[RFC] OpenSearch Sentence Transformer Model Training Feature  in opensearch-py-ml

### ISSUE THREAD

**Issue by mingshl** [opensearch-project/opensearch-py-ml#29]
Problem Statement:

Models are only as good as the data they’re trained on. The selected models have been trained on large corpuses of public data, and in the process have learned the vocabulary and semantics from these corpuses. Some use cases such as Enterprise search requires the ability to perform search on private domain information. These models will likely require training on these datasets in order to perform well.

Unfortunately, training large language models like GPT-2 from scratch is expensive, time consuming and difficult. A common technique to alleviate this issue involves fine-tuning pre-trained models. This involves incrementally training these models on the target search corpus, and allows modelers to deliver better models using small datasets and significantly less training time.  

Sentence Transformer Model class in opensearch-py-ml package is built for python programmers to use as a frame work to train/fine tune sentence transformer models, and prepare the custom model to upload to OpenSearch cluster. 

The main functionality of this feature is to provide a default framework to automatically train/fine tune sentence transformer model based on (query, document)-training data, including reading synthetic query data, loading pre-train model, configuring accelerator, training model with/without accelerator, outputting as TorchScript model and saving as zip file. 

* Simple and efficient tools for sentence transformer model training
* open-source and reusable in various contexts
* freedom to modify, extend and monetize

Sample Use Cases

We assume that the user has synthetic queries - (query, document)-training data in a zip file, aiming at generating a customized semantic search model for inferencing searching results. 

Proposed Solution

With a synthetic queries zip file, users can import opensearch_py_ml package to fine tune a sentence transformer model to train a semantic search model. The train function will import synthestic queries, load sentence transformer example and train the model using a hugging face sentence transformer model. The synthetic queries zip file should contain pickled file in list of dictionary format with key named as 'query','probability' and 'passages'. For example: [{'query':q1,'probability': p1,'passages': pa1}, ...].'probability' is not required for training purpose.

```
import opensearch_py_ml as oml
from opensearchpy import OpenSearch
from opensearch_py_ml.sentence_transformer_model import SentenceTransformerModel
from opensearch_py_ml.ml_commons_integration import MLCommonClient

# Load a Hugging Face transformers model directly from the model hub and start training 
# with accelerate using 1 gpu
model = SentenceTransformerModel()
training = model.train(read_path = 'synthethic_queries.zip',
                       model_id = 'sentence-transformers/msmarco-distilbert-base-tas-b',
                       output_model_name = 'trained_model',
                       zip_file_name= 'zip_model',
                       use_accelerate  = True,  
                       num_machines = 1,
                       num_processes = 1,
                       verbose = True)
                       
# Import trained model into OpenSearch 
CLUSTER_URL = 'https://localhost:9200'

def get_os_client(cluster_url = CLUSTER_URL,
                  username='admin',
                  password='admin'):
    '''
    Get OpenSearch client
    :param cluster_url: cluster URL like https://ml-te-netwo-1s12ba42br23v-ff1736fa7db98ff2.elb.us-west-2.amazonaws.com:443
    :return: OpenSearch client
    '''
    client = OpenSearch(
        hosts=[cluster_url],
        http_auth=(username, password),
        verify_certs=False
    )
    return client
    
client = get_os_client() 
ml_client = MLCommonClient(client)
model_path = 'zip_model.zip'
model_name = 'semantic_search_model_v1'
ml_client.put_model( model_path, model_name, 1, verbose=True)
```

**Comment by dhrubo-os** [comment]
This feature is already available in `1.0.0` release
