### ISSUE TITLE
[FEATURE] update model group

### ISSUE THREAD

**Issue by dhrubo-os** [opensearch-project/opensearch-py-ml#290]
In 2.8, we introduces [model access control](https://opensearch.org/docs/latest/ml-commons-plugin/model-access-control/) in ml-commons. But we didn't extend this functionality in opensearch-py-ml yet.

We want to add update_model_group: https://opensearch.org/docs/latest/ml-commons-plugin/model-access-control/#updating-a-model-group
 
request parameters: https://opensearch.org/docs/latest/ml-commons-plugin/model-access-control/#request-fields-1

example request: https://opensearch.org/docs/latest/ml-commons-plugin/model-access-control/#example-request-1

example response: https://opensearch.org/docs/latest/ml-commons-plugin/model-access-control/#example-response

**Comment by wuzhijing0127** [comment]
Can I work on this issue?

**Comment by dhrubo-os** [comment]
Sure, assigned it to you.

**Comment by dhrubo-os** [comment]
@wuzhijing0127 Do you have any update on this issue?

**Comment by dhrubo-os** [comment]
@wuzhijing0127 Due to the urgency and no update from you, I'm going to assign this issue to @rawwar

@rawwar could you please comment in this issue, so that I can assign it to you?
