### ISSUE TITLE
[FEATURE] Delete model group

### ISSUE THREAD

**Issue by dhrubo-os** [opensearch-project/opensearch-py-ml#292]
In 2.8, we introduces [model access control](https://opensearch.org/docs/latest/ml-commons-plugin/model-access-control/) in ml-commons. But we didn't extend this functionality in opensearch-py-ml yet.

We want to add delete_model_group: https://opensearch.org/docs/latest/ml-commons-plugin/model-access-control/#deleting-a-model-group

example request: https://opensearch.org/docs/latest/ml-commons-plugin/model-access-control/#example-request-2

example response: https://opensearch.org/docs/latest/ml-commons-plugin/model-access-control/#example-response-4

**Comment by Dantochi** [comment]
Please could you be a little clearer... 🙏

**Comment by wuzhijing0127** [comment]
Can I work on this issue?

**Comment by dhrubo-os** [comment]
@wuzhijing0127 let's pick issue one by one? I think I already assigned you to an [issue](https://github.com/opensearch-project/opensearch-py-ml/issues/290)

**Comment by Sylviama1026** [comment]
@dhrubo-os Could I be assigned to this issue?

**Comment by dldisha** [comment]
@dhrubo-os can I work on this issue?

**Comment by dhrubo-os** [comment]
Sure, assigning it to you.

**Comment by dhrubo-os** [comment]
@dldisha Do you have any question on this issue? Any update?

**Comment by dhrubo-os** [comment]
@dldisha Due to the urgency and no update from you, I'm going to assign this issue to @rawwar 

@rawwar could you please comment in this issue, so that I can assign it to you?

**Comment by rawwar** [comment]
@dhrubo-os , please assign me this issue.
