### ISSUE TITLE
[BUG] Pandas import error: cannot import name 'is_datetime_or_timedelta_dtype' from 'pandas.core.dtypes.common'

### ISSUE THREAD

**Issue by faradawn** [opensearch-project/opensearch-py-ml#306]
**What is the bug?**
When running the third cell of the [first demo notebook](https://opensearch-project.github.io/opensearch-py-ml/examples/demo_notebook.html), I cannot import pandas:
```
import opensearch_py_ml as oml

-> ImportError: cannot import name 'is_datetime_or_timedelta_dtype' from 'pandas.core.dtypes.common' 
```

Here is a screenshot:

<img width="857" alt="Screenshot 2023-10-05 at 9 59 21 AM" src="https://github.com/opensearch-project/opensearch-py-ml/assets/73060648/18839bac-1a88-4ef0-80a4-f4eba0fda7a5">

**How can one reproduce the bug?**
Follow the dev guide: https://github.com/opensearch-project/opensearch-py-ml/blob/main/DEVELOPER_GUIDE.md
```
# Create a fork
git clone https://github.com/faradawn/opensearch-py-ml.git
cd opensearch-py-ml

# Install dependencies
python3 -m venv env
source env/bin/activate
pip install -r requirements-dev.txt
```
**What is the expected behavior?**
Should import successfully

**What is your host/environment?**
- Intel Mac 13.2.1 (22D68)
- opensearch-py 2.3.1
- pandas 2.1.1
- python 3.9.6
- pip 23.2.1

**Comment by dhrubo-os** [comment]
We already have an issue opened about it: https://github.com/opensearch-project/opensearch-py-ml/issues/263

**Comment by dhrubo-os** [comment]
@faradawn can we close this issue in favor of https://github.com/opensearch-project/opensearch-py-ml/issues/263

**Comment by dtaivpp** [comment]
@faradawn you can resolve this by pinning pandas to 2.0.3

**Comment by faradawn** [comment]
Thanks @dtaivpp and @dhrubo-os! I can confirm that the error disappear when downgrading pandas to 2.0.3:
```
pip install pandas==2.0.3
```
Appreciate the help!

**Comment by grofte** [comment]
@faradawn 

Haha, that didn't get me much farther but thank you for trying

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/mog/tiger/cost-center-ai/src/train_model/03_deploy_model_pipeline.py", line 12, in <module>
    from opensearch_py_ml.ml_commons import MLCommonClient
  File "/home/mog/tiger/cost-center-ai/.venv/lib/python3.12/site-packages/opensearch_py_ml/ml_commons/__init__.py", line 10, in <module>
    from opensearch_py_ml.ml_commons.ml_commons_client import MLCommonClient
  File "/home/mog/tiger/cost-center-ai/.venv/lib/python3.12/site-packages/opensearch_py_ml/ml_commons/ml_commons_client.py", line 13, in <module>
    from deprecated.sphinx import deprecated
ModuleNotFoundError: No module named 'deprecated'
```

Actually that turned out to be the name of a package. `uv add deprecated` sorted me out.
