### ISSUE TITLE
[BUG] `deprecated` library missing from `install_requires` list

### ISSUE THREAD

**Issue by miguelsousa** [opensearch-project/opensearch-py-ml#315]
**What is the bug?**
The `deprecated` library is used in [ml_commons_client.py](https://github.com/opensearch-project/opensearch-py-ml/blob/901bcd44e00a52ea31d9837065537b22ea96cc93/opensearch_py_ml/ml_commons/ml_commons_client.py#L13) but `opensearch-py-ml` doesn't install it by default.

**How can one reproduce the bug?**
1. Install `opensearch-py-ml`
2. Use `from opensearch_py_ml.ml_commons import MLCommonClient` in your code
3. `ModuleNotFoundError` happens
```
Traceback (most recent call last):
  File "client.py", line 24, in <module>
    from opensearch_py_ml.ml_commons import MLCommonClient
  File "lib/python3.10/site-packages/opensearch_py_ml/ml_commons/__init__.py", line 10, in <module>
    from opensearch_py_ml.ml_commons.ml_commons_client import MLCommonClient
  File "lib/python3.10/site-packages/opensearch_py_ml/ml_commons/ml_commons_client.py", line 13, in <module>
    from deprecated.sphinx import deprecated
ModuleNotFoundError: No module named 'deprecated'
```

**What is the expected behavior?**
No crash.

**Proposed fix**
Add `deprecated` to `install_requires` in **setup.py**.

**Comment by Vinay-Vinod** [comment]
Can I be assigned to this issue?

**Comment by dhrubo-os** [comment]
Sure, assigning it to you.

**Comment by wuzhijing0127** [comment]
Can I be assigned to this issue?

**Comment by dhrubo-os** [comment]
@wuzhijing0127 this issue is already assigned to @Vinay-Vinod and he also raised a PR. Please ping me if you don't see any other issue. Thanks.
