### ISSUE TITLE
[FEATURE] search model group

### ISSUE THREAD

**Issue by rawwar** [opensearch-project/opensearch-py-ml#333]
Along with update model group(#290) ,register model group( #289) , we can add search model group functionality to Model Access Control Class

**Comment by rawwar** [comment]
@dhrubo-os , regarding search model group, it seems we can do this via a [POST or GET](https://opensearch.org/docs/latest/ml-commons-plugin/model-access-control/#path-and-http-method-2). Wondering if there's a difference between these two? Can we go ahead with just GET?

**Comment by dhrubo-os** [comment]
> @dhrubo-os , regarding search model group, it seems we can do this via a [POST or GET](https://opensearch.org/docs/latest/ml-commons-plugin/model-access-control/#path-and-http-method-2). Wondering if there's a difference between these two? Can we go ahead with just GET?

@rbhavna Could you please tell if there's any difference between two during search?

@rawwar We can go with GET for now.
