### ISSUE TITLE
[BUG] `MLCommonClient_client.upload_model` passes wrong arguments to `register_model`

### ISSUE THREAD

**Issue by rawwar** [opensearch-project/opensearch-py-ml#335]
**What is the bug?**
`MLCommonClient_client.upload_model` passes wrong arguments to `register_model`.

current code:

```
def upload_model(
        self,
        model_path: str,
        model_config_path: str,
        isVerbose: bool = False,
        load_model: bool = True,
        wait_until_loaded: bool = True,
    ) -> str:
        
        model_id = self._model_uploader._register_model(
            model_path, model_config_path, isVerbose
        )

        # loading the model chunks from model index
        if load_model:
            self.load_model(model_id, wait_until_loaded=wait_until_loaded)

        return model_id
```

In the above code, isVerbose is passed as 3rd argument. But,  `_register_model` definition is as follows:

```
def _register_model(
        self,
        model_path: str,
        model_meta_path: str,
        model_group_id: str = "",
        isVerbose: bool = False,
    )
```

Hence, the code is passing `isVerbose` value to `model_group_id`. This is wrong.

**Comment by grofte** [comment]
To anyone that runs into `model_group_id` problems with MLCommons client. If you are like me you have missed that `.upload_model()` is deprecated. It also does not work. Use `.register_model()` instead. As a bonus you can deploy the model easily in the same call.
