### ISSUE TITLE
[FEATURE] Remove pin on the pandas version in nox tests

### ISSUE THREAD

**Issue by rawwar** [opensearch-project/opensearch-py-ml#339]
Currently, `nox` tests pin `1.5.0` version of pandas for tests. We should be removing this and actually testing with the version mentioned in the `requirements.txt`

https://github.com/opensearch-project/opensearch-py-ml/blob/fc698a746e482b73f5c32cc68de199ba6398f902/noxfile.py#L106

**Comment by mvarlamov222** [comment]
I can take this issue.

**Comment by rawwar** [comment]
@mvarlamov222 , You would need to run tests after removing the version pin. Then, preferably mention the issues you see. Fixing them will close this issue.

**Comment by rawwar** [comment]
@mvarlamov222 , do you need any help in completing this? If you can raise a draft PR with your work, I can probably help you out.

**Comment by mvarlamov222** [comment]
> @mvarlamov222 , do you need any help in completing this? If you can raise a draft PR with your work, I can probably help you out.

Sorry, something has been wrong with my computer lately and sometimes it's working and at times it isn't. I made some changes, but I am not confident that they fix the issue, I can commit them today.
