### ISSUE TITLE
[FEATURE] Langchain Template for RAG using Opensearch

### ISSUE THREAD

**Issue by dhrubo-os** [opensearch-project/opensearch-py-ml#341]
We need to work on this issue: https://github.com/langchain-ai/langchain/issues/13295

We can see if we can also integrate opensearch-py-ml as a dependency there [not urgent]

**Comment by rawwar** [comment]
Will be working on this.

**Comment by rawwar** [comment]
PR for the issue i s here - langchain-ai/langchain#13501

**Comment by dhrubo-os** [comment]
@rawwar Thanks for working on this.
