### ISSUE TITLE
[FEATURE] Pin all packages versions in `requirements.txt` and `requirements-dev.txt` 

### ISSUE THREAD

**Issue by rawwar** [opensearch-project/opensearch-py-ml#367]
**Is your feature request related to a problem?**
Currently, multiple packages are missing pins. Hence, they will be installed differently based on the available latest versions of the individual packages. This is not a deterministic installation. Hence, we can add min and max version pins to avoid breaking changes.

**What solution would you like?**
Pin all packages

**Comment by Yerzhaisang** [comment]
What if we have one file to export package versions, so requirements.txt and requirements-dev.txt, ci tests can import package versions from this file?

**Comment by dhrubo-os** [comment]
Closing this issue in respect of https://github.com/opensearch-project/opensearch-py-ml/pull/383
