### ISSUE TITLE
[FEATURE] enhance model_uploader workflow to support BGE models from huggingface

### ISSUE THREAD

**Issue by zhichao-aws** [opensearch-project/opensearch-py-ml#387]
**Is your feature request related to a problem?**
In OpenSearch we support some sentence-transformers model as [pretrained models](https://opensearch.org/docs/latest/ml-commons-plugin/pretrained-models/#sentence-transformers). The registration of pretrained models is much more convenient, and users don't need to change the cluster settings plugins.ml_commons.allow_registering_model_via_url.

With the development of the research and engineering evolution in IR domain, now there are much stronger text_embedding models in the open source community. ([leaderboard ref](https://huggingface.co/spaces/mteb/leaderboard)) However, users still need to trace these models and generate the tarball manually, which is a heavy workload especially for those with little machine-learning background knowledge.

**What solution would you like?**
BGE models(https://huggingface.co/BAAI/bge-small-en-v1.5, https://huggingface.co/BAAI/bge-base-en-v1.5, https://huggingface.co/BAAI/bge-large-en-v1.5) have very strong text_embedding representation among the models with same size. And we can use them consistently with other sentence-transformers text_embedding models. 

Considering the models will consume resources in local deployment, We can support  bge-small-en-v1.5 and bge-base-en-v1.5 as pretrained models in OpenSearch.

**What alternatives have you considered?**

**Do you have any additional context?**
https://github.com/opensearch-project/ml-commons/issues/2210

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)

**Comment by zhichao-aws** [comment]
We need to deprecate this work item as the model use Reddits as training data
