### ISSUE TITLE
[FEATURE] Model autotracing workflow for sparse encoding model.

### ISSUE THREAD

**Issue by conggguan** [opensearch-project/opensearch-py-ml#395]
**Is your feature request related to a problem?**
There have some need to publish sparse encoding pre-trained models. But now [opensearch-py-ml](https://github.com/opensearch-project/opensearch-py-ml) only support text embedding models' autotracing workflow.

**What solution would you like?**
Add a workflow for sparse encoding model's auto tracing and release.

**What alternatives have you considered?**

**Do you have any additional context?**
[OpenSearch pre-trained models](https://opensearch.org/docs/latest/ml-commons-plugin/pretrained-models/#sparse-encoding-models)
[Neural sparse encoding model v1](https://huggingface.co/opensearch-project/opensearch-neural-sparse-encoding-v1)

**Comment by conggguan** [comment]
Feel free to assign this issue to me @congguan.

**Comment by dhrubo-os** [comment]
@conggguan We can close this issue, right?
