### ISSUE TITLE
[FEATURE] Parse model config information from Huggingface 

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/opensearch-py-ml#43]
When user upload model, they need to provide model config json file. For Huggingface model, it's possible to parse these json content from Hugginface model config file. Refer to https://opensearch.org/docs/latest/ml-commons-plugin/model-serving-framework/#upload-model-to-opensearch

One possible solution:
When we export Huggingface model, parse Huggingface model config file and write a new model config file for ml-commons.

**Comment by Yerzhaisang** [comment]
is this issue already solved or in progress?

**Comment by thanawan-atc** [comment]
@ylwu-amzn Should we close this issue? I believe `make_model_config_json` can now do this for `sentence-transformer` model.

**Comment by ylwu-amzn** [comment]
Thanks, I think we can close this issue now as it's already supported.
