### ISSUE TITLE
[FEATURE] Support run pytorch traced model on GPU

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/opensearch-py-ml#47]
We plan to support GPU in ml-commons for model serving framework GA release. I see current py-ml code is using CPU here https://github.com/opensearch-project/opensearch-py-ml/blob/main/opensearch_py_ml/sentence_transformer_model/sentencetransformermodel.py#L525. Does that mean the model can't support GPU?

**Comment by dhrubo-os** [comment]
Model traced in CPU.

Model loaded and generated embedding in CPU & GPU.
