### ISSUE TITLE
[BUG] Failed to establish a new connection: [Errno 61] Connection refused when trying to import

### ISSUE THREAD

**Issue by mfarrelm** [opensearch-project/opensearch-py-ml#68]
**What is the bug?**
Cannot import the library. I got this error
```ConnectionError: ConnectionError(<urllib3.connection.HTTPSConnection object at 0x144b90940>: Failed to establish a new connection: [Errno 61] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPSConnection object at 0x144b90940>: Failed to establish a new connection: [Errno 61] Connection refused)```

**What is your host/environment?**
 - OS: MacOS 13,0,1
 - Version 1.0.0b1

**Comment by mfarrelm** [comment]
Okay after I dig into the code, I think the version is still not updated with this commit f353dfaa038f1c153b1ca1966477dcbb72eb98dd, so this line is still in the ```opensearch_py_ml/common.py``` after I installed the library
```python
OPENSEARCH_HOST = "https://instance:9200"
OPENSEARCH_ADMIN_USER, OPENSEARCH_ADMIN_PASSWORD = "admin", "admin"

# Define client to use in tests
OPENSEARCH_TEST_CLIENT = OpenSearch(
    hosts=[OPENSEARCH_HOST],
    http_auth=(OPENSEARCH_ADMIN_USER, OPENSEARCH_ADMIN_PASSWORD),
    verify_certs=False,
)
# in github integration test, host url is: https://instance:9200
# in development, usually host url is: https://localhost:9200
#it's hard to remember changing the host url. So applied a try catch so that we don't have to keep change this config
try:
    OS_VERSION = os_version(OPENSEARCH_TEST_CLIENT)
except opensearchpy.exceptions.ConnectionError:
    OPENSEARCH_HOST = "https://localhost:9200"
    # Define client to use in tests
    OPENSEARCH_TEST_CLIENT = OpenSearch(
        hosts=[OPENSEARCH_HOST],
        http_auth=(OPENSEARCH_ADMIN_USER, OPENSEARCH_ADMIN_PASSWORD),
        verify_certs=False,
    )
    OS_VERSION = os_version(OPENSEARCH_TEST_CLIENT)
```

**Comment by dhrubo-os** [comment]
Hi, the beta version expects to have a opensearch connection already which we are going to change in our next GA version(this will be releasing soon).

**Comment by dhrubo-os** [comment]
Hi, [mfarrelm](https://github.com/mfarrelm), `1.0.0` is released. Can you please upgrade the version?

I'm closing the issue for now. Please feel free to open if version upgrade doesn't work for you. Thanks.
