### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-py-ml#81]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by gaiksaya** [comment]
Please onboard to 2PR approval process after CODEOWNER's file is updated. 
Details: https://github.com/opensearch-project/opensearch-build/issues/3111
Sample PR: https://github.com/opensearch-project/opensearch-java/pull/383

**Comment by dblock** [comment]
There are 18+ people with actual maintain permissions. Please work with an admin to adjust to match MAINTAINERS and CODEOWNERS.

<img width="828" alt="Screenshot 2023-03-30 at 10 28 50 AM" src="https://user-images.githubusercontent.com/542335/228869054-6618f397-c128-4ea0-82a2-90489a7b9c92.png">

**Comment by dhrubo-os** [comment]
@dblock,

with the help of admin we cleaned up the permission. 

Now only @dhrubo-os & @ylwu-amzn is having the "Maintain" role. 

Please let me know if that looks good to you. 

Thanks.

**Comment by dblock** [comment]
Verified, thanks.
